export const BRANDS = [
    { name: "Apple", logo: "🍎", slug: "apple" },
    { name: "Samsung", logo: "📱", slug: "samsung" },
    { name: "Xiaomi", logo: "MI", slug: "xiaomi" },
    { name: "Google", logo: "G", slug: "google" },
    { name: "OnePlus", logo: "1+", slug: "oneplus" },
    { name: "Tecno", logo: "T", slug: "tecno" },
]

export const PRODUCTS = [
    {
        id: "lumina-zx",
        name: "Lumina ZX Flagship",
        brand: "SmartHub",
        price: 1199,
        originalPrice: 1299,
        image: "/images/lumina_zx.png",
        images: ["/images/lumina_zx.png", "/images/lumina_fold.png", "/images/lumina_zx.png"],
        rating: 4.9,
        reviews: 124,
        tags: ["New", "5G", "Flagship"],
        category: "Smartphones",
        stock: 15,
        description: "The pinnacle of mobile engineering with a triple-lens system and celestial display.",
        specs: {
            display: '6.8" AMOLED 120Hz',
            processor: "Snapdragon 8 Gen 4",
            battery: "5500mAh",
            camera: "200MP Main",
            ram: "12GB",
            storage: "512GB",
            os: "Android",
            network: "5G",
            condition: "New"
        }
    },
    {
        id: "lumina-fold",
        name: "Aurora Fold Pro",
        brand: "SmartHub",
        price: 1799,
        originalPrice: 1999,
        image: "/images/lumina_fold.png",
        images: ["/images/lumina_fold.png", "/images/lumina_zx.png", "/images/lumina_fold.png"],
        rating: 4.8,
        reviews: 86,
        tags: ["Foldable", "Premium"],
        category: "Smartphones",
        stock: 8,
        description: "Unfold the future with the most durable flexible display ever made.",
        specs: {
            display: '7.6" Foldable AMOLED',
            processor: "Snapdragon 8 Gen 4",
            battery: "4800mAh",
            camera: "108MP Main",
            ram: "16GB",
            storage: "1TB",
            os: "Android",
            network: "5G",
            condition: "New"
        }
    },
    {
        id: "iphone-16-pro",
        name: "iPhone 16 Pro Max",
        brand: "Apple",
        price: 1299,
        image: "/images/lumina_zx.png", 
        images: ["/images/lumina_zx.png", "/images/lumina_fold.png"],
        rating: 4.9,
        reviews: 432,
        tags: ["Popular"],
        category: "Smartphones",
        stock: 25,
        description: "Titanium design and A18 Pro chip for unparalleled performance.",
        specs: {
            display: '6.9" Super Retina XDR',
            processor: "A18 Pro",
            battery: "4685mAh",
            camera: "48MP Fusion",
            ram: "8GB",
            storage: "256GB",
            os: "iOS",
            network: "5G",
            condition: "New"
        }
    },
    {
        id: "s24-ultra",
        name: "Galaxy S24 Ultra",
        brand: "Samsung",
        price: 1099,
        originalPrice: 1199,
        image: "/images/lumina_zx.png",
        images: ["/images/lumina_zx.png", "/images/lumina_fold.png"],
        rating: 4.7,
        reviews: 215,
        tags: ["AI Powered", "5G"],
        category: "Smartphones",
        stock: 12,
        isSale: true,
        description: "The ultimate AI-first smartphone experience with S-Pen support.",
        specs: {
            display: '6.8" Dynamic AMOLED',
            processor: "Snapdragon 8 Gen 3",
            battery: "5000mAh",
            camera: "200MP Pro-Grade",
            ram: "12GB",
            storage: "256GB",
            os: "Android",
            network: "5G",
            condition: "New"
        }
    },
    {
        id: "macbook-pro-m3",
        name: "MacBook Pro M3 Max",
        brand: "Apple",
        price: 2499,
        image: "/images/lumina_zx.png",
        images: ["/images/lumina_zx.png"],
        rating: 4.9,
        reviews: 89,
        tags: ["Pro", "M3 Max"],
        category: "Laptops",
        stock: 5,
        description: "The most powerful laptop for professional workflows.",
        specs: {
            display: '16.2" Liquid Retina XDR',
            processor: "Apple M3 Max",
            battery: "22 Hours",
            camera: "1080p FaceTime HD",
            ram: "32GB",
            storage: "1TB",
            os: "macOS",
            network: "Wi-Fi 6E",
            condition: "New"
        }
    },
    {
        id: "ipad-pro-m4",
        name: "iPad Pro M4 Ultra",
        brand: "Apple",
        price: 999,
        image: "/images/lumina_zx.png",
        images: ["/images/lumina_zx.png"],
        rating: 4.8,
        reviews: 156,
        tags: ["OLED", "Thin"],
        category: "Tablets",
        stock: 20,
        description: "Incredibly thin. Outrageously powerful.",
        specs: {
            display: '11" Ultra Retina Tandem OLED',
            processor: "Apple M4",
            battery: "10 Hours",
            camera: "12MP Wide",
            ram: "8GB",
            storage: "256GB",
            os: "iPadOS",
            network: "5G",
            condition: "New"
        }
    },
    {
        id: "airpods-max-2",
        name: "AirPods Max 2",
        brand: "Apple",
        price: 549,
        image: "/images/lumina_zx.png",
        images: ["/images/lumina_zx.png"],
        rating: 4.6,
        reviews: 210,
        tags: ["Audio", "ANC"],
        category: "Accessories",
        stock: 35,
        isSale: true,
        description: "The ultimate personal listening experience.",
        specs: {
            display: 'Acoustically Optimized Mesh',
            processor: "H2 Chip",
            battery: "20 Hours",
            camera: "External ANC Mics",
            ram: "N/A",
            storage: "N/A",
            os: "Proprietary",
            network: "Bluetooth 5.3",
            condition: "New"
        }
    }
]
